namespace dm.ffmods.raidersdroploot
{
    public enum LootItem
    {
        //animalTrap,
        arrow,

        basket,
        beans,
        berries,
        boarCarcass,

        //books,
        bow,

        bread,
        brick,
        candle,
        carcass,
        cheese,
        clay,

        //clover,
        coal,

        crossbow,
        eggs,
        fireWood,
        fish,
        flax,
        flour,
        fruit,
        furniture,
        glass,
        goldIngot,
        goldOre,
        grain,
        greens,
        hauberk,
        heavyWeapon,
        herbs,
        hideCoat,
        hide,
        honey,
        ironOre,
        linenClothes,
        logs,
        meat,
        medicine,
        milk,
        mushroom,
        nuts,

        //paper,
        planks,

        platemail,
        pottery,
        preservedVeg,
        preserves,
        roots,
        sand,
        shield,
        shoes,
        simpleWeapon,
        smallCarcass,
        smokedFish,
        smokedMeat,
        soap,
        stone,
        tallow,
        tool,
        water,
        wax,
        weapon,
        wheatBeer,
        willow,
        wolfCarcass
    }
}